### ISSUE TITLE
installation on macOS fails

### ISSUE THREAD

**Issue by rettinghaus** [proycon/codemetapy#3]
`pip install codemetapy` fails with following message 
```
Collecting codemetapy
  Downloading https://files.pythonhosted.org/packages/ad/7f/5b1c63961441b77cb0a1b266a2bed616697c89af785281371e8be072793c/CodeMetaPy-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-bT1rfX/codemetapy/setup.py", line 22, in <module>
        long_description=read('README.rst'),
      File "/private/tmp/pip-install-bT1rfX/codemetapy/setup.py", line 10, in read
        return open(os.path.join(os.path.dirname(__file__), fname),'r',encoding='utf-8').read()
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-bT1rfX/codemetapy/
```

**Comment by proycon** [comment]
I guess you are running on Python 2? Codemetapy is for Python 3 only currently.

**Comment by rettinghaus** [comment]
Perhaps you could add a hint towards python 3 somewhere? (not only in the codemeta.json)

And please change the first line in `setup.py` to
`#!/usr/bin/env python3`

Most system should then figure out automatically.
